config/routes.rb
Rails.application.routes.draw do

  get 'signup'  => 'users#new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  resources :urls, only:[:index, :new, :create, :show, :edit, :update]
  resources :pages
  resources :users
  resources :categories
  
  get '/urls/:slug', to: 'urls#show', as: :slug
  namespace "api", defaults: { format: 'json' } do
    resources :urls
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @url = Url.new
    10.times { @url.images.build }
    10.times { @url.webs.build }
    10.times { @url.personals.build }
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | SNPPR</title>
  </head>
  <body>
    <h1>About</h1>
    <p align="left">SNPPR is a web application that makes the process of sending multiple images and web links to your contacts into a much more intuitive and less frustrating experience.</p>
    <br>
    <p align="left">Just drag-and-drop images from the web or even your local computer into the box on the page and your images are ready to be sent to your contacts.</p>
	<br>
    <p align="left">The images will display on one page complete with a customized URL.</p>
	<br>
    <p align="left">You can even send links to web pages with your images to give a richer and more informative experience.</p>
	<br>
    <p align="left">SNPPR is perfect for sending images of shopping lists, vacation ideas, montages as well as any type of information sharing.</p>
	<br>
    <p align="left">Instead of copying and pasting multiple links, just drag-and-drop the images onto the SNPPR input page and click Submit.</p>
	<br>
    <h3>Never has sharing images and links been easier!</h3>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>Have a question, comment or general feedback about SNPPR?</p>
<p>Send an email to us <a href="SNPPR@noemailyet.com">here</a> and we'll respond as soon as we can.</p>
<h3>Thanks for your interest in SNPPR!</h3>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | SNPPR</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
    Experiencing an issue with SNPPR?  Check this page in the very near-future for answers to your questions and information about contacting SNPPR support.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Try it now or <%= link_to "sign up", signup_path, class: "btn btn-lg btn-success" %> to save your urls</h1>
<script language="javascript">
    document.addEventListener("DOMContentLoaded", function(){
    
    document.onload = startup();
    
    function startup() {
        //All personal upload input fields are displayed none to start with. At startup I want to show the first one
        showPersonal();
     }
    
    //Initialize the variables and set the dropbox to the dropzone and add even listeners to listen for drag and drop 
    var personals;
    var imgList;
    var personalUpload = $('.show.personal .files');
    var dropbox = document.getElementById('dropbox');
    dropbox.addEventListener('dragenter', noopHandler, false);
    dropbox.addEventListener('dragexit', noopHandler, false);
    dropbox.addEventListener('dragover', noopHandler, false);
    dropbox.addEventListener('drop', drop, false);
    personalUpload.on("change", showPersonalAttributes);
    
    //noopHandler cancels the natural events of the event listeners we described above 
    function noopHandler(evt) {
        evt.stopPropagation();
        evt.preventDefault();
    }
   
    //on drop of an object, the drop function gets called and passes the event. The event is then parsed for the dataTransfer and filters out the image URLs from the uploaded files. 
    function drop(evt) {
        var obj = evt.dataTransfer;
        if(obj){
          var obj = evt.dataTransfer;
          evt.stopPropagation();
          evt.preventDefault();
          if(obj.getData){
            imgList = obj.getData('URL');
            if (checkURL(imgList)){
                addImage(imgList); 
                hideBackground();
            }
            else {
              $('.drop-background').attr("class", "drop-background");
              alert("File Type not accepted in this dropbox, try the upload below")
              $('.drop-background').attr("class", "drop-background");
            }
            
          }
          else{
            alert("File Type not accepted in this dropbox");
          }
        }
        else{
          alert("There was an error with this submission");
        }
    }
   
    //ALL input fields are hidden in the background and filled in when the object is dropped into the dropzone. The follwoing methods add the links to the input field and/or show the fields for desktop uploads or background image of the dropzone. 
   
    function addImage(link){
        document.querySelector('.none.image input.empty').value = link; 
        document.querySelector('.none.image input.empty').className = "filled";  
        var node = document.createElement('li');
        node.innerHTML = link;
        document.querySelector('#list-preview').appendChild(node);
    }
    
    function addWeb(link){
        document.querySelector('.none.web input').value = link;
        document.querySelector('.none.web').className = "";
    }
    
    function showPersonal(){
        $('.none.personal').first().attr("class", "show personal");

    }

    function hidePersonal(){
        $('.show.personal').first().attr("class", "none-filled personal");

    }

    function showPersonalAttributes(){
        $('.show.personal .none.personal-title').attr("class", "personal-title form-control");
        $('.show.personal .none.personal-alt').attr("class", "personal-alt form-control");
    }

    function hideBackground(){
        $('.drop-background').attr("class", "none drop-background");
    }

    //This function checks to see if the URL is an image or a web URL
    function checkURL(url) {
        return(url.match(/\.(jpeg|jpg|gif|png)$/) != null);
    }
     
    //This jQuery ajax call is triggered once the user once to create a url. It takes all the input values of the form and transfers the data as a hash to our api and responds back with the data.
    $('#loading-btn').click(function () {
        var btn = $(this)
        var title = $('#url_title').val();
        var images = $('.image input.filled');
        var webs = $('.web input.filled');
        var personals = $('.show.personal input.files'); 
        var category = $('.category-collect').val();
        var params = {url:[]}
        $('.none.drop-background').attr("class", "drop-background");
        $('#list-preview').empty();
        dataString = params['url'].push({title: title, images_attributes: images, webs_attributes: webs, personal_attributes: personals, category_id: category});      
        $.ajax({
            type: "POST",
            url: "/api/urls/",
            beforeSend: function(xhr) {xhr.setRequestHeader("Accept", "text/javascript")},
            data: dataString,
            dataType: 'html',
            success: function(data, textStatus){
              console.log(data);
            }

        });
    });
  
    //This method will add any URLs you copy and paste to our dropzone or files uploaded from your desktop. It also checks to see if you are trying to both or none at the same time and will alert you to only upload once at a time.  
    $('#addQueue').click(function(){
        hideBackground();
        var textArea = $('textarea').val();
        var personalInput = $('.show.personal input.files').val();
        var input;
        if (textArea != "" && personalInput == ""){
            input = textArea;
        }
        else if (personalInput != "" && textArea == ""){
            input = personalInput;
        }
        else if (personalInput != "" && textArea != ""){
            alert("You can only add one item to the Queue at a time");
            return
        }
        else{
            alert("You cannot add an empty item!");
            return
        }
        
        if (checkURL(input)){
            addImage(input);
            $('textarea').val("");
        }
        else { 
            $('.none.web input.empty').first().val(input);
            $('.none.web input.empty').first().attr('class', 'filled');
            $('textarea').val("");
            $('#list-preview').append("<li>" + input + "</li>");
            showPersonal(); 
            hidePersonal();
            var personalUpload = $('.show.personal .files');
            personalUpload.on("change", showPersonalAttributes);
        }
    });
  });
</script>

<div class="container form">
  <div class="row form">
    <%= form_for @url, html: { multipart: true, class: 'form-group dropbox-form' }, remote: true do |u| %>
      <% if logged_in? %>
        <%= u.text_field :title, placeholder: "Shorten URL Title" , class: 'form-control' %>
        <%= u.collection_select :category_id, @category, :id, :title %>
      <% end %>
      <%= u.fields_for :images do |i| %>
        <div class="none image">
          <%= i.text_field :link, class: 'empty form-control', placeholder: "IMAGE URL" %>
        </div>
      <% end %>  
      <%= u.fields_for :webs do |w| %>
        <div class="none web" id="webs">
          <%= w.text_field :link, class: 'empty form-control', placeholder: "WEB URL" %>
        </div>
      <% end %>
      <div id="dropbox">
        <div id="top-preview">
          <ol id="list-preview">
          </ol>
          <div class="drop-background">
            <span class="glyphicon glyphicon-picture"></span>
            <h2>DRAG AND DROP HERE</h2>
            <h6>(drag or upload desktop images below)</h6>
          </div>
        </div>
        <textarea rows="5"  placeholder="USE THIS AREA TO COPY AND PASTE URL PAGES OR IMAGE URLS AND ADD TO QUEUE WITH BUTTON BELOW"></textarea>
          <%= u.fields_for :personals do |p| %>
          <div class="none personal">
            <%= p.text_field :title, class: 'personal-title none', placeholder: 'Title of desktop uploaded image' %>
            <%= p.text_field :alt_text, class: 'personal-alt none', placeholder: 'Alt Text of desktop uploaded image' %>
            <%= p.file_field :image, class: 'files form-control' %>
          </div>
          <% end %>
      <%= u.submit("CREATE URL", class: 'btn btn-success', id: 'loading-btn') %>
    <% end %> 
    <input class="btn btn-success add-queue" id="addQueue" type="button" value="ADD TO QUEUE">
      </div>
  </div>
</div>

app/views/static_pages/home.js.erb
$('form').prepend('<p>Your url: <%= link_to( "http://snppr.ly/#{@url.slug}", slug_path(@url.slug), method: 'get') %></p>'); 