config/routes.rb
Rails.application.routes.draw do

  get 'signup'  => 'users#new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  resources :urls, only:[:index, :new, :create, :show, :edit, :update]
  resources :pages
  resources :users
  resources :categories
  
  get '/urls/:slug', to: 'urls#show', as: :slug
  namespace "api", defaults: { format: 'json' } do
    resources :urls
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

	belongs_to :user
	has_many :urls
	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
# before_action :set_category, only: [:show, :edit, :update, :destroy]

#Setting the necessary methods for the Categories function in SNPPR.

	def index
	end

	def new
		@category = Category.new
	end

	def create
	  @category = Category.create(category_params)
    @category.user_id = current_user.id	  

    if @category.save
	    redirect_to user_path(current_user)
	  else
	   	render :new
		end
	end

	def show
		@category = Category.find(params[:id])
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private
		# def set_category
	 #      @category = Category.find(params[:id])
	 #    end

		def category_params
			params.require(:category).permit(:title)
		end

end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

<% provide(:title, "Edit Category") %>
<h1>Update your category title</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:category, url: edit_category_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :title %>
      <%= f.text_field :title, %>

      <p>
      </p>

      <%= f.submit "Edit Category", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

<% provide(:title, "New Category") %>
<h1>New Category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:category, url: new_category_path) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <p>
      </p>

      <%= f.submit "Create Category", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>
<% provide(:title, @user.user_name) %>
<h1>
  <%= @user.user_name %>
</h1>